apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
  labels:
    dev.macnichol: application
spec:
  generators:
    - git:
        repoURL: git@github.com:cmacnichol/avalon.git
        revision: HEAD
        directories:
          - path: k8s/apps/dev/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.macnichol: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: dev
      source:
        repoURL: git@github.com:cmacnichol/avalon.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true