apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external
  namespace: argocd
spec:
  sourceRepos:
    - 'git@github.com:cmacnichol/avalon.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'haos'
      server: '*'
    - namespace: 'proxmox'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'